{% set name = "quetz-client" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quetz_client-{{ version }}.tar.gz
  sha256: 2494d292d0d163dfa181bc0342b8f630ec150315c17412f1aee8b5ab03cc08d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - quetz-client = quetz_client.cli:main

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - fire
    - requests

test:
  imports:
    - quetz_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mamba-org/quetz-client
  description: A Python client to interact with a Quetz server.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
    - janjagusch
