{% set name = "quetz-client" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TheSnakePit/quetz/archive/client_v{{ version }}.tar.gz
  sha256: 87106d8385f563feb1ef1d437c8d6a3fbf9ddeea449f9815da34f2f4fdd3f768

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install ./quetz_client --no-deps -vv
  entry_points:
    - quetz-client = quetz_client:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - requests >=2,<3
    - conda-verify >=3,<4
    - conda-build >=3,<4

test:
  imports:
    - quetz_client
  commands:
    - quetz-client -h

about:
  home: https://github.com/TheSnakePit/quetz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client for the Quetz package server

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
